function normKey(k){return String(k??'').replace(/^\uFEFF/,'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');}
function field(row,names){const m={};Object.entries(row||{}).forEach(([k,v])=>m[normKey(k)]=v);for(const name of names){const v=m[normKey(name)];if(v!==undefined&&v!==null&&String(v).trim()!=='')return v;}return '';}
function amount(value){if(value===null||value===undefined||value==='')return 0;let v=String(value).trim().replace(/\u00a0/g,'').replace(/\s/g,'');if(!v)return 0;if(v.includes(',')&&v.includes('.')){if(v.lastIndexOf(',')>v.lastIndexOf('.'))v=v.replace(/\./g,'').replace(',','.');else v=v.replace(/,/g,'');}else if(v.includes(','))v=v.replace(',','.');const n=Number(v.replace(/[^0-9.+-]/g,''));return Number.isFinite(n)?n:0;}
function account(row){return String(field(row,['CompteNum','Compte','Account','Compte numéro'])).replace(/\D/g,'');}
function dateIso(row){const raw=String(field(row,['EcritureDate','Date','DateEcriture'])).trim();const m=raw.match(/^(\d{4})[-/]?(\d{2})[-/]?(\d{2})/);return m?`${m[1]}-${m[2]}-${m[3]}`:'';}
function compute(rows){
 const accounts=new Map(),months=new Map(),dates=new Set();let parsedLines=0;
 for(const r of rows){const a=account(r);if(!/^\d{3,8}$/.test(a))continue;const d=amount(field(r,['Debit','Débit'])),c=amount(field(r,['Credit','Crédit']));const cur=accounts.get(a)||{debit:0,credit:0,balance:0};cur.debit+=d;cur.credit+=c;accounts.set(a,cur);const iso=dateIso(r);if(iso){dates.add(iso);const mm=iso.slice(0,7);const map=months.get(mm)||new Map();const mv=map.get(a)||{debit:0,credit:0,balance:0};mv.debit+=d;mv.credit+=c;map.set(a,mv);months.set(mm,map);}parsedLines++;}
 const amountForMap=(map,prefixes,mode='creditMinusDebit')=>{let total=0;map.forEach((v,a)=>{if(!prefixes.some(p=>a.startsWith(p)))return;const net= v.balance || (mode==='debitMinusCredit'?v.debit-v.credit:v.credit-v.debit);total+=net;});return total;};
 const amountFor=(prefixes,mode='creditMinusDebit')=>amountForMap(accounts,prefixes,mode);
 const buildMonthMetrics=(map)=>{const ca=amountForMap(map,['70','71','72']);const purchases=amountForMap(map,['60','61','62'],'debitMinusCredit');const external=amountForMap(map,['63'],'debitMinusCredit');const payroll=amountForMap(map,['64'],'debitMinusCredit');const ebe=ca-purchases-external-payroll;const rex=ca-amountForMap(map,['60','61','62','63','64','65','68'],'debitMinusCredit')+amountForMap(map,['75','78']);const result=ca-amountForMap(map,['60','61','62','63','64','65','66','67','68','69'],'debitMinusCredit')+amountForMap(map,['75','76','77','78','79']);return{ca,ebe,rex,resultat_net:result};};
 const revenue=amountFor(['70','71','72']);const purchases=amountFor(['60','61','62'],'debitMinusCredit');const external=amountFor(['63'],'debitMinusCredit');const payroll=amountFor(['64'],'debitMinusCredit');const ebe=revenue-purchases-external-payroll;const rex=revenue-amountFor(['60','61','62','63','64','65','68'],'debitMinusCredit')+amountFor(['75','78']);const resultAccount=amountFor(['120','129','12']);const resultat_net=Math.abs(resultAccount)>0.01?resultAccount:revenue-amountFor(['60','61','62','63','64','65','66','67','68','69'],'debitMinusCredit')+amountFor(['75','76','77','78','79']);const tresorerie_nette=amountFor(['512','53'])-amountFor(['519'],'debitMinusCredit');const actifsCourtTerme=amountFor(['31','32','33','34','35','37','40','41','42','43','44','46','47','48'],'debitMinusCredit');const passifsCourtTerme=amountFor(['40','41','42','43','44'],'creditMinusDebit');const bfr=actifsCourtTerme-passifsCourtTerme;const liquidite_generale=passifsCourtTerme?actifsCourtTerme/Math.abs(passifsCourtTerme):0;
 const account_balances=Object.fromEntries([...accounts.entries()].map(([a,v])=>[a,Number(v.balance||(v.credit-v.debit)||0)]));const sorted=[...dates].sort();const monthsCovered=new Set(sorted.map(d=>d.slice(0,7))).size;const monthly_metrics=Object.fromEntries([...months.entries()].map(([m,map])=>[m,buildMonthMetrics(map)]));
 return{source:'',imported_at:new Date().toISOString(),lines:rows.length,parsed_lines:parsedLines,months_covered:monthsCovered,period_start:sorted[0]||null,period_end:sorted.at(-1)||null,is_partial_year:monthsCovered>0&&monthsCovered<12,accounts_detected:accounts.size,ca:revenue,valeur_ajoutee:revenue-purchases-external,ebe,rex,resultat_net,bfr,tresorerie_nette,liquidite_generale,gearing:0,roe:0,account_balances,monthly_metrics};
}
function groupYear(rows){const groups=new Map();for(const r of rows){const iso=dateIso(r);const y=iso.slice(0,4);const key=/^20\d{2}$/.test(y)?y:'unknown';const arr=groups.get(key)||[];arr.push(r);groups.set(key,arr);}return groups;}
export function buildNovacabFinancialKpis(rows=[],fileName=''){
 const groups=groupYear(rows);const byYear={};for(const [year,group] of groups){if(year==='unknown')continue;const k=compute(group);k.source=fileName;k.imported_at=new Date().toISOString();byYear[year]=k;}if(!Object.keys(byYear).length){const k=compute(rows);k.source=fileName;k.imported_at=new Date().toISOString();const m=fileName.match(/20\d{2}/g);byYear[m?.at(-1)||String(new Date().getFullYear())]=k;}return byYear;
}
