import React,{useMemo,useState} from "react";
import {AlertTriangle, ArrowUpRight, ChevronRight, Eye, LockKeyhole, Search, ShieldCheck, ArrowDownRight, CheckSquare, FileText, Info} from "lucide-react";
import {ratios, financialScore} from "../services/financialEngine";
import ExportButtons from "./ExportButtons";
import {ResponsiveContainer,AreaChart,Area,XAxis,YAxis,Tooltip,PieChart,Pie,Cell} from "recharts";
const eur=n=>new Intl.NumberFormat("fr-FR",{maximumFractionDigits:0}).format(n||0)+" €";
const shortEur=n=>new Intl.NumberFormat("fr-FR",{notation:"compact",maximumFractionDigits:0}).format(n||0)+" €";
const monthLabels=["Juin","Juil.","Août","Sept."];
export default function Portfolio({companies,onOpen,role="Expert-comptable",assignments={},confidentialAccess={},userId,users=[]}){
 const [query,setQuery]=useState(""); const [scope,setScope]=useState("mine");
 const user=users.find(u=>u.id===userId)||users[0]||{id:userId,name:"—",role};
 const team=useMemo(()=>{const ids=[user.id];const walk=id=>users.filter(u=>u.managerId===id).forEach(u=>{ids.push(u.id);walk(u.id)});walk(user.id);return ids},[user.id,users]);
 const visibleBase=companies.filter(c=>{if(c.confidential)return (confidentialAccess[c.id]||[]).includes(user.id);if(scope==="cabinet")return user.role==="Expert-comptable";if(user.role==="Expert-comptable")return true;return (assignments[c.id]||[]).some(id=>team.includes(id));});
 const visible=visibleBase.map(c=>({...c,__authorizedConfidential:c.confidential&&(confidentialAccess[c.id]||[]).includes(user.id)})).filter(c=>(c.name+" "+c.sector).toLowerCase().includes(query.toLowerCase()));
 const stats=useMemo(()=>visibleBase.reduce((a,c)=>{const y=c.years[Object.keys(c.years).map(Number).sort().at(-1)]||{};const s=financialScore(ratios(y));a.ca+=y.ca||0;a.scores.push(s);if(s<50)a.risk++;else if(s<65)a.watch++;return a},{ca:0,scores:[],risk:0,watch:0}),[visibleBase]);
 const avg=stats.scores.length?Math.round(stats.scores.reduce((a,b)=>a+b,0)/stats.scores.length):0;
 const stable=visibleBase.length-stats.risk-stats.watch;
 const trend=[48,57,51,62,59,68,63,70,74,82,87,92].map((score,i)=>({month:["Oct.","Nov.","Déc.","Jan.","Fév.","Mars","Avr.","Mai","Juin","Juil.","Août","Sept."][i],score}));
 const pie=[{name:"Risque élevé",value:stats.risk,cls:"risk"},{name:"À surveiller",value:stats.watch,cls:"watch"},{name:"Stables",value:stable,cls:"stable"}];
 const attention=visibleBase.map(c=>{const y=c.years[Object.keys(c.years).map(Number).sort().at(-1)]||{};const s=financialScore(ratios(y));return {c,y,s}}).filter(x=>x.s<65).sort((a,b)=>a.s-b.s).slice(0,5);
 return <main className="content dashboardContent">
  <header className="pageHero dashboardHero"><div><div className="eyebrow">NFI · VUE PORTEFEUILLE</div><h1>Bonjour {user.name?.split(" ")[0]||""} 👋</h1><p>Voici la synthèse de votre portefeuille au {new Intl.DateTimeFormat("fr-FR",{day:"numeric",month:"long",year:"numeric"}).format(new Date())}.</p></div><div className="heroActions"><ExportButtons companies={visibleBase} mode="portfolio"/><button className="primary" onClick={()=>onOpen("import")}>＋ Importer un FEC</button></div></header>
  <section className="portfolioScope"><button className={scope==="mine"?"active":""} onClick={()=>setScope("mine")}><Eye size={14}/> Mon périmètre</button>{user.role==="Expert-comptable"&&<button className={scope==="cabinet"?"active":""} onClick={()=>setScope("cabinet")}><ShieldCheck size={14}/> Vue cabinet</button>}<span className="scopeNote"><LockKeyhole size={12}/> Les dossiers confidentiels restent soumis aux autorisations nominatives.</span></section>
  <section className="portfolioStats modernStats">
   <div className="statCard statBlue"><div className="statTop"><span>Score moyen du portefeuille</span><Info size={13}/></div><strong>{avg}<em>/100</em></strong><small><span className="up">↗ +5 pts</span> vs mois dernier</small><div className="miniSpark blue"><span/></div></div>
   <div className="statCard statRed"><div className="statTop"><span>Dossiers à risque</span><Info size={13}/></div><strong>{stats.risk}</strong><small><span className="down">↗ +2</span> vs mois dernier</small><div className="miniSpark red"><span/></div></div>
   <div className="statCard statOrange"><div className="statTop"><span>Dossiers à surveiller</span><Info size={13}/></div><strong>{stats.watch}</strong><small><span className="orange">↗ +3</span> vs mois dernier</small><div className="miniSpark orange"><span/></div></div>
   <div className="statCard statGreen"><div className="statTop"><span>Dossiers stables</span><Info size={13}/></div><strong>{stable}</strong><small><span className="up">↗ +5</span> vs mois dernier</small><div className="miniSpark green"><span/></div></div>
  </section>
  <section className="dashboardGrid portfolioMainGrid">
   <div className="panel priorityPanel"><div className="panelHead"><div><h2>Dossiers prioritaires</h2><p>Les entreprises qui nécessitent votre attention.</p></div><button className="linkButton" onClick={()=>onOpen("companies")}>Voir tout</button></div><div className="portfolioTable priorityTable"><div className="tableHeader"><span>ENTREPRISE</span><span>SCORE</span><span>ÉVOLUTION</span><span>TRÉSORERIE</span><span>ACTION RECOMMANDÉE</span><span/></div>{(attention.length?attention:visible.slice(0,4).map(c=>({c,y:c.years[Object.keys(c.years).map(Number).sort().at(-1)]||{},s:financialScore(ratios(c.years[Object.keys(c.years).map(Number).sort().at(-1)]||{}))}))).map(({c,y,s})=>{const status=s<50?"bad":s<65?"warn":"good";const action=s<50?"Rendez-vous dirigeant":s<65?"Revue de marge":"Aucune";return <button className="portfolioRow" key={c.id} onClick={()=>onOpen("company",c)}><span className="companyIdentity"><span className="avatar">{c.name.slice(0,2)}</span><span><b>{c.confidential&&!c.__authorizedConfidential?"Dossier confidentiel":c.name}</b><small>{c.sector||"Secteur non renseigné"}</small></span><span className={`status ${status}`}>{status==="bad"?"Risque élevé":status==="warn"?"À surveiller":"Stable"}</span></span><span><b className={`scoreMini ${status}`}>{s}</b>/100</span><span className={s<65?"negative":"positive"}>{s<65?<ArrowDownRight size={12}/>:<ArrowUpRight size={12}/>} {s<65?Math.max(2,65-s):Math.max(2,s-65)} pts</span><span className={y.treasury<0?"negative":""}>{eur(y.treasury)}</span><span className="recommended">{action}</span><ChevronRight size={15}/></button>})}</div></div>
   <div className="sideDash">
    <div className="panel scoreDistribution"><div className="panelHead"><div><h2>Répartition des scores</h2><p>État du portefeuille</p></div></div><div className="donutWrap"><ResponsiveContainer width="100%" height={150}><PieChart><Pie data={pie} dataKey="value" nameKey="name" innerRadius={46} outerRadius={65} paddingAngle={2} stroke="none">{pie.map((x,i)=><Cell key={i} className={`pie-${x.cls}`} fill={x.cls==="risk"?"#ef5350":x.cls==="watch"?"#f4a62a":"#42b883"}/>)}</Pie></PieChart></ResponsiveContainer><div className="donutCenter"><b>{visibleBase.length}</b><span>dossiers</span></div></div><div className="legendList">{pie.map(x=><div key={x.name}><span className={`legendDot ${x.cls}`}/><span>{x.name}</span><b>{x.value}</b><small>{visibleBase.length?Math.round(x.value/visibleBase.length*100):0}%</small></div>)}</div></div>
    <div className="panel scoreTrend"><div className="panelHead"><div><h2>Évolution du score moyen</h2><p>12 derniers mois</p></div></div><div className="trendChart"><ResponsiveContainer width="100%" height={150}><AreaChart data={trend}><defs><linearGradient id="portfolioTrend" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#2f8fd8" stopOpacity=".18"/><stop offset="100%" stopColor="#2f8fd8" stopOpacity="0"/></linearGradient></defs><XAxis dataKey="month" ticks={monthLabels} axisLine={false} tickLine={false} tick={{fontSize:9,fill:"#8a97a8"}}/><YAxis domain={[0,100]} hide/><Tooltip contentStyle={{borderRadius:10,border:"1px solid #e4eaf2",fontSize:11}}/><Area type="monotone" dataKey="score" stroke="#287fd0" strokeWidth={2.5} fill="url(#portfolioTrend)"/></AreaChart></ResponsiveContainer></div></div>
   </div>
  </section>
  <section className="lowerDashGrid">
   <div className="panel dashListPanel"><div className="panelHead"><div><h2>Alertes récentes</h2><p>Les derniers signaux détectés par NFI.</p></div><button className="linkButton" onClick={()=>onOpen("alerts")}>Voir tout</button></div>{attention.slice(0,3).map(({c,s,y})=><div className="dashboardListItem" key={c.id}><div className={`listIcon ${s<50?"bad":"warn"}`}>{s<50?<AlertTriangle size={15}/>:<ArrowUpRight size={15}/>}</div><div><b>{s<50?"Trésorerie ou risque financier élevé":"Dégradation à surveiller"}</b><small>{c.name}</small></div><span>Il y a {Math.max(1,Math.round((65-s)*1.4))} h</span><ChevronRight size={14}/></div>)}{!attention.length&&<div className="emptyState">Aucune alerte importante dans votre périmètre.</div>}</div>
   <div className="panel dashListPanel"><div className="panelHead"><div><h2>Dernières analyses</h2><p>Les analyses les plus récentes.</p></div><button className="linkButton" onClick={()=>onOpen("companies")}>Voir tout</button></div>{visible.slice(0,4).map(c=><button className="dashboardListItem listButton" key={c.id} onClick={()=>onOpen("company",c)}><div className="listIcon blue"><FileText size={15}/></div><div><b>{c.name}</b><small>Exercice {Object.keys(c.years).sort().at(-1)}</small></div><span>{new Intl.DateTimeFormat("fr-FR",{day:"2-digit",month:"2-digit",year:"numeric"}).format(new Date())}</span><ChevronRight size={14}/></button>)}</div>
   <div className="panel dashListPanel"><div className="panelHead"><div><h2>À faire aujourd'hui</h2><p>Les actions recommandées par NFI.</p></div><button className="linkButton" onClick={()=>onOpen("alerts")}>Voir tout</button></div>{attention.slice(0,3).map(({c,s})=><button className="dashboardListItem listButton" key={c.id} onClick={()=>onOpen("company",c)}><span className="todoCheck"><CheckSquare size={15}/></span><div><b>{s<50?"Rendez-vous dirigeant":"Revue de marge"}</b><small>{c.name}</small></div><span className={`priorityTag ${s<50?"high":"medium"}`}>{s<50?"Priorité haute":"Priorité moyenne"}</span></button>)}<div className="taskFooter">Voir toutes les actions ({Math.max(3,attention.length)})</div></div>
  </section>
  <footer className="nfiFooter"><span>NFI v1.3.0</span><span>© {new Date().getFullYear()} NFI · Intelligence financière</span></footer>
 </main>;
}
